# Generated by Django 4.2.2 on 2023-07-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_car_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_of_purchase',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='odometer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='car',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle'),
        ),
        migrations.AddField(
            model_name='car',
            name='purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
